[package]
name = "youtuber"
description = "A CLI to search for and watch YouTube through the terminal"
repository = "https://github.com/JJGOD-13/youtuber"
version = "0.1.0"
edition = "2024"
license = "MIT"
keywords = ["cli", "youtube", "ratatui"]
include = ["src/"]
readme = "README.md"


[dependencies]
ratatui = "0.30.0"
tui-input = "0.15.3"
rustypipe = "0.11.4"
tokio = { version = "^1.20.0", features = ["macros", "rt-multi-thread"] }
tracing-error = "0.2.1"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
directories = "6.0.0"
lazy_static = "1.5.0"
color-eyre = "0.6.5"
which = "8.0.2"
